# Numpy basics

In [16]:
import numpy as np

# !pip install numpy

In [ ]:
# list
numbers = [1,3.0,4,5,6, "a", True]
numbers

[1, 3, 4, 5, 6, 'a', True]

In [18]:
# numpy array
numbers = np.array([1,3,4,5,6])
type(numbers)
numbers

array([1, 3, 4, 5, 6])

# why numpy array instead of python list

In [24]:
# using list
numbers = [1, 2, 3, 4]

# This doesn't multiply individual elements
print(numbers * 3)

new_numbers = [number * 3 for number in numbers]
print(new_numbers)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[3, 6, 9, 12]


In [23]:
numbers = np.array([1,2,3,4])
print(numbers * 2)

[2 4 6 8]


numpy provides vectorized operations,  making numerical operation efficient and fast

## creating numpy array

In [25]:
# 1d array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [30]:
# 2d array
arr2 = np.array([
    [1, 2, 3], 
    [3, 4, 5]
    ])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

0D -> scalar

1D -> vector

2D -> matrix

3D+ -> tensor/multidimisional array

In [46]:
# 2d array
arr2 = np.array([
    [1, 2, 2], 
    [3, 4, 3]
    ])

# number of diminsion
arr2.ndim

2

In [47]:
# shape of each dim
arr2.shape

(2, 3)

In [48]:
# total number of elements
arr2.size

6

In [49]:
# types of element
arr2.dtype

dtype('int64')

In [51]:
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

arr.shape


(3, 2)

In [54]:
# zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [58]:
# arange (same like range in python list)
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# with step
with_step = np.arange(1,10,2)
with_step

array([1, 3, 5, 7, 9])

In [63]:
arr2

array([[1, 2, 2],
       [3, 4, 3]])

## numpy indexing

In [68]:
print(arr2[1][2])
print(arr2[0][1])
print(arr2[1])

3
2
[3 4 3]


## slicing in numpy

arr[start:stop:step]

In [74]:
arr = np.array([1,2,3,4,5,6,7,9])
print(arr[1:4])
print(arr[3:7])
print(arr[:5])
print(arr[3:])
print(arr[::2])

[2 3 4]
[4 5 6 7]
[1 2 3 4 5]
[4 5 6 7 9]
[1 3 5 7]


In [79]:
# for 2d arry
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr2[0:2, 1:3])

[[20 30]
 [50 60]]


# mathematical operation

In [105]:
arr = np.array([1,2,3,4,5])

print(arr * 2)
print(arr ** 2)
print(arr + 2)

avg = np.mean(arr)
print(arr[arr>avg])

[ 2  4  6  8 10]
[ 1  4  9 16 25]
[3 4 5 6 7]
[4 5]


In [88]:
arr1 = np.array([2,3,4,5,6])
print(arr + arr1)
print(arr1 - arr)
print(arr/arr1)
print(arr * arr1)

[ 3  5  7  9 11]
[1 1 1 1 1]
[0.5        0.66666667 0.75       0.8        0.83333333]
[ 2  6 12 20 30]


In [98]:
# max used numpy functions
marks = np.array([56,89,90,34,50,45])

# average marks
print(np.mean(marks))

# total marks
print(np.sum(marks))

# min marks
print(np.min(marks))

# max marks
print(np.max(marks))

# median marks
print(np.median(marks))

# stadard deviation
print(np.std(marks))

60.666666666666664
364
34
90
53.0
21.429470880593907


# Temperature Analysis

In [100]:
temp = np.array([21, 25, 28, 30, 27, 24, 22])
# calculate avg, max, min, temp above avg

# Sales Analysis

### each row represents sales man, and each col represents month

- Print the array dimensions.
- Print its shape.
- Find total sales.
- Find average sales.
- Find the highest sale.
- Find the lowest sale.
- Calculate total sales for each salesperson.
- Calculate total sales for each month.
- Find all sales greater than 1500.
- Increase every sales value by 10% and print the resulting array.

In [104]:
sales = np.array([
    [1200, 1500, 1100],
    [1800, 1700, 1600],
    [900, 1200, 1400],
    [2000, 2100, 1900]
])

In [110]:
# sales value increase by 10%
print(sales * 1.1)

[[1320. 1650. 1210.]
 [1980. 1870. 1760.]
 [ 990. 1320. 1540.]
 [2200. 2310. 2090.]]
