## Boolean indexing / filtering

In [2]:
import numpy as np

arr = np.array([1,2,3,43,4,5,6])
print(arr > 5)

[False False False  True False False  True]


In [4]:
print(arr[arr > 5])

[43  6]


In [11]:
arr = np.array([10, 25, 30, 45, 50, 65])

print(arr[(arr < 30) & (arr < 60)])

[10 25]


## np.where()

In [14]:
marks = np.array([35, 67, 42, 89, 28])

result = np.where(marks >= 40, "Pass", "Fail")
print(result)

['Fail' 'Pass' 'Pass' 'Pass' 'Fail']


In [18]:
salary = np.array([25000, 40000, 55000, 30000])

new_salary = np.where(salary <= 40000, salary*1.2, salary*1.1)
print(new_salary)

[30000. 48000. 60500. 36000.]


## sorting

In [23]:
arr = np.array([50, 20, 80, 10, 40])

# asending
print(f"ascnding: {np.sort(arr)}")

# descending
print(f"descending: {np.sort(arr)[::-1]}")

ascnding: [10 20 40 50 80]
descending: [80 50 40 20 10]


In [26]:
# argsort() - returns index instead of values
print(np.argsort(arr))

[3 1 4 0 2]


## unique values

In [28]:
cities = np.array([
    "Kathmandu",
    "Pokhara",
    "Kathmandu",
    "Chitwan",
    "Pokhara"
])

print(np.unique(cities))

['Chitwan' 'Kathmandu' 'Pokhara']


In [29]:
cities = ["Kathmandu", "Pokhara", "Kathmandu", "Chitwan", "Pokhara"]
unique_cities = list(set(cities))
print(unique_cities)

['Chitwan', 'Pokhara', 'Kathmandu']


In [32]:
# count occurances
values, count = np.unique(cities, return_counts=True)
print(values)
print(count)

['Chitwan' 'Kathmandu' 'Pokhara']
[1 2 2]


## missing value - NaN

In [33]:
data = np.array([10, 20, np.nan, 40, 50])

print(data)

[10. 20. nan 40. 50.]


In [40]:
print(np.mean(data))

new_data = np.where(np.isnan(data), 0.0, data)
new_data

nan


array([10., 20.,  0., 40., 50.])

In [42]:
# detect missing values
print(np.isnan(data))

[False False  True False False]


In [44]:
# removing nan values
print(data[~np.isnan(data)])

[10. 20. 40. 50.]


## Random numbers

In [53]:
rng = np.random.default_rng()

print(rng.random(5))

[0.61096078 0.11698256 0.05652008 0.7154287  0.13401145]


In [54]:
print(rng.integers(1, 1000, size=20))

[486 385 844 461 161 661 216 873 755 296 993 302 119 348 607  26 699 761
 107 243]


In [65]:
# 2d random numbers
print(rng.integers(10000, 100000, size=(5, 12)))

[[44208 37071 36267 73503 74146 68951 31610 21347 17824 81412 14697 94532]
 [69603 11780 71655 96769 78037 35168 69020 63671 78088 33289 89696 65142]
 [44547 26075 26607 15296 46080 45156 47886 21242 54467 53363 81343 93745]
 [32861 23136 62639 61586 58043 82755 17449 39691 98213 27152 69707 23459]
 [87977 54524 60708 11442 19992 59219 99887 67376 82765 22882 31692 45808]]


In [79]:
# reproducible random numbers
rng = np.random.default_rng(42)
result = rng.integers(100, 1000, size=10)
print(result)

[180 796 689 494 489 872 177 727 281 184]


## student performance analaysis
```code
marks = np.array([
    [65, 70, 75],
    [80, 85, 90],
    [45, 55, 60],
    [90, 95, 92],
    [35, 40, 50],
    [72, 68, 75],
    [88, 82, 84],
    [55, 60, 58]
])
```
columns: Python | Mathematics | Statistics

### calculate
1. Average mark of every student
2. Average mark of every subject
3. Highest mark in the dataset
4. Lowest mark
5. Student with highest average
6. Students whose Python mark is above 70
7. Number of individual marks above 80
8. Students with an overall average below 50
9. Sort students based on overall average
10. Assign a result using:
```code 
Average >= 80     → Distinction
Average >= 60     → First Division
Average >= 40     → Pass
Average < 40      → Fail
```

In [95]:
# 10 assign results
marks = np.array([
    [65, 70, 75],
    [80, 85, 90],
    [45, 55, 60],
    [90, 95, 92],
    [35, 40, 50],
    [72, 68, 75],
    [88, 82, 84],
    [55, 60, 58],
    [10, 20, 30],
])

# average mark of every subject
sub_avg = np.mean(marks, axis=0)
print(sub_avg)

# student wise
std_avg = np.mean(marks, axis=1)
print(std_avg)

results = np.select(
    [
        std_avg >= 80,
        std_avg >= 60,
        std_avg >= 40
    ],
    [
        'Distinction',
        "First Division",
        "Pass"
    ],
    default="Fail"
)

print(results)

[60.         63.88888889 68.22222222]
[70.         85.         53.33333333 92.33333333 41.66666667 71.66666667
 84.66666667 57.66666667 20.        ]
['First Division' 'Distinction' 'Pass' 'Distinction' 'Pass'
 'First Division' 'Distinction' 'Pass' 'Fail']
